[package]
name = "brclock"
version = "0.1.0"
edition = "2021"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
unwrap_used = "warn"
# expect_used = "warn"

[dependencies]
chrono = "0.4.38"
dynfmt = { version = "0.1.5", features = ["curly"] }
